### ISSUE TITLE
Add tests to RAIL/estimation

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/rail_attic#12]
write tests (and potentially automate with GitHub actions) for the estimation branch of RAIL

**Comment by johannct** [comment]
I am starting on this.... Did you started on your side? 
I have some comments from a first attempt at running main : 
 - we need a complete internal functional sequence, with possibly a random concrete estimator, and an included or easily downloadable training data set.
- if the config includes the algo name to be used, then the user should not have to have all the algos actually installed; Currently the call to 'import algos' in main.py enforces import of all the modules within algos/ which means all the external codes like flexCode.
- Currently the name of the algo to be selected is found by parsing the name of the yaml file. I do not think that this is viable. It should be a string or a list of strings in the yaml file. A user might want to run several of them......

**Comment by sschmidt23** [comment]
Thanks, Johann, I have not started on the tests, feel free to create a new branch and start putting together some tests, that would be appreciated.  If you come up with a list of some tests that we want to implement, feel free to add them to this issue with [ ] boxes, then I can see about contributing some code.

For now I have been using the tomo_challenge "mini" train and test sets just because they were conveniently already made.  We could easily grab a few small subsets of the cosmoDC2_v1.1.4_image data where we added mock 10 year errors as well for training/validation/testing.

I believe I set up the loading of all algorithms as a check that nothing major had been broken, but you're correct, it does put a bit of an extra burden on the setup and package dependencies even for those wishing to use only one or two algorithms.  

I'm not super happy with the parsing of the yaml file name to set which code to run, and particularly requiring that it match the code name, as it makes running slight variations of parameters with the same code a bit tricky.  I originally had the code/subclass to be run as an argument in the config yaml file, I think Alex must have changed this at some point, maybe we should think about switching it back?

**Comment by aimalz** [comment]
Thanks @johannct and @sschmidt23!  I think there are only a few remaining tasks (some of which may be punted to #3, but they look easier to do together for this branch):


- [x] The test data in [a top-level examples directory outside `rail`](https://github.com/LSSTDESC/RAIL/tree/origin/issue/3/estimation-template/jct/examples) left over from when we had a `ceci` dependency should be removed because there's now also test data [where the tests live](https://github.com/LSSTDESC/RAIL/tree/origin/issue/3/estimation-template/jct/rail/estimation/tests/data).
- [x] We should probably include a README with that test data to credit its creators and/or include the script that isolated it from the public tomo_challenge data.
- [x] The example in [the estimation module](https://github.com/LSSTDESC/RAIL/tree/origin/issue/3/estimation-template/jct/rail/estimation/example) should replace the now-defunct example in [that top-level examples directory outside `rail`](https://github.com/LSSTDESC/RAIL/tree/origin/issue/3/estimation-template/jct/examples), which will require changing some path stuff that I never quite got working myself when I tried last month.
- [x] While [`algos`](https://github.com/LSSTDESC/RAIL/tree/origin/issue/3/estimation-template/jct/rail/estimation/algos) should be a submodule of `rail.estimator`, the [`configs`](https://github.com/LSSTDESC/RAIL/tree/origin/issue/3/estimation-template/jct/rail/estimation/configs) directory shouldn't be a submodule and so belongs outside `rail` in [the top-level `examples` directory](https://github.com/LSSTDESC/RAIL/tree/origin/issue/3/estimation-template/jct/examples).
- [x] We should automate testing.  If there aren't any Travis CI aficionados here, I'd probably just copy the Travis CI setup from [CLMM](https://github.com/LSSTDESC/CLMM), which would involve moving the `tests` directory now living in [the `estimation` module outside of `rail`](https://github.com/LSSTDESC/RAIL/tree/origin/issue/3/estimation-template/jct/examples) (and might also require setting up an `__init__.py` [outside of the `estimation` module](https://github.com/LSSTDESC/RAIL/tree/origin/issue/3/estimation-template/jct/examples), which is just one step away from enabling a proper `setup.py` installation anyway).

Did I miss anything?

As for the code name parsing, I did that while trying to split the `base.yaml` of parameters we as experimenters set, which would include paths to all relevant files, and the config parameters for each code, which wouldn't even be the same fields.  It seemed redundant to have a keyword for the name when it's already repeated all over the place, but I can also think of situations where we'd want it to be different, say, for testing a single estimator subclass's sensitivity to its config parameters.

**Comment by johannct** [comment]
First bullet : is there any testing to salvage from there, before nuking it?
Second bullet : I do not catch what you have in mind, @aimalz . Perhaps you take it over using this branch?

**Comment by sschmidt23** [comment]
I looked at the old example directory at the top level of `rail`, nothing there needs to be salvaged, it's from the old `generic pipe` form that we abandoned. 
I will copy the script that generated the test data, which should cover bullet point 2

**Comment by johannct** [comment]
embryo of setup.py pushed as per 0c2f580

**Comment by johannct** [comment]
looks like the check list above has a first implementation working in origin/issue/3/estimation-template  and essentially ready to merge, so closing this issue.
