### ISSUE TITLE
Add Brier Score metric to evaluate

### ISSUE THREAD

**Issue by jbkalmbach** [LSSTDESC/rail_attic#125]
Implement Brier Score metric in RAIL.evaluate.

**Comment by drewoldag** [comment]
As I work through this as a ramp up project, and since the details of the request as a little sparse, I'm working with a few assumptions, that I would like to get some clarity on. First of all, I'm assuming that this request is for a Brier metric applied to predicted vs. true redshift specifically. 

The other assumption that I'm working with is that this isn't the discrete Brier metric as described in wikipedia article (https://en.wikipedia.org/wiki/Brier_score#Original_definition_by_Brier). But is more equivalent to calculating the mean square error. 

If I could get some clarification on those assumptions, that would be very much appreciated.

Conditioned on clarification of those two point, defining the expected inputs/outputs would be very helpful too.

**Comment by drewoldag** [comment]
After a conversation with @jbkalmbach I got some addition information about the requirements, and cleared up my incorrect assumptions. Outlining the conversation here for posterity.

The input to the function will be two arrays (`prediction` and `truth`) each of which will be NxM in size. These will represent N celestial objects and M redshift bins. For a given row, representing a celestial object, in the `truth` array, all M bins will be 0's with the exception of the bin that contains the true redshift which will have the value of 1. For a given row in the `prediction` array for a given celestial object, each of the M bins will contain the predicted probability that the redshift is contained within that bin. 

A remaining open question here (input from @aimalz would be appreciated) is whether to expect the user to have manipulated the data structures into the required form prior to passing them into the function, or if the function should also handle data manipulation.

**Comment by drewoldag** [comment]
I've created this PR: https://github.com/LSSTDESC/RAIL/pull/262

If either @aimalz or @jbkalmbach could take a look at it, it would be very much appreciated.
