### ISSUE TITLE
re-implement the TXPipe implementation of NZDir in RAIL

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/rail_attic#130]
This is already roughly done, I just forgot to create an issue, the code is in the u/sschmidt23/nzdir branch, internals are a little rough but it's functional (see demo notebook in that branch in examples/summarization/NZDir.ipynb), I'll finish fixing this up once I am back from vacation/LINCC conference.

**Comment by aimalz** [comment]
Thanks for starting this @sschmidt23! A few things:

[The current stage](https://github.com/LSSTDESC/RAIL/blob/u/sschmidt23/nzdir/rail/estimation/algos/NZDir.py) includes a binning step that we should omit, as RAIL inputs should always be pre-binned. 

Also, I thought the DIR method would have been a CatSummarizer subclass, but the implementation is a CatEstimator subclass. I'm confused because it looks like [the demo](https://github.com/LSSTDESC/RAIL/blob/u/sschmidt23/nzdir/examples/estimation/NZDir.ipynb) is showing it performing as a summarizer, too. Would it be hard to change that?

(Super-unimportant side note: do we care about uniformity of using caps in module names?)
