### ISSUE TITLE
Factor out algorithms that have complicated dependencies

### ISSUE THREAD

**Issue by eacharles** [LSSTDESC/rail_attic#232]
Gonna try moving those to their own packages, and make an umbrella package to pull in everything.

**Comment by eacharles** [comment]
Hi All, after speaking with @sschmidt23 and following up on discussions at the collaboration meeting I’m going to propose some restructuring of rail in order to better manage the dependencies.  

1. We’d like to split out three of the estimators that bring in more dependencies into their own packages.  This will make it easier for people developing the various degraders.   Specifically we would like to have rail_delight , rail_bpz, and rail_flexzboost , each of which just has the relevant estimator and test code.     
2. We’d like to add an umbrella package to collect all of the various packages, for the uses who do want everything.   This would be rail_top 
3. We’d like to add two packages to collect various analysis pipelines to make it easier to run productions jobs at NERSC, these would be rail_pipelines and rail_pipe_configs.  This first would have python code and notebeooks to run the pipelines iteractively or in notebooks, i.e., for development.  The second would have production configurations to run rail at NERSC under ceci.
4. Making this work will require a few changes to the RAIL package.   The most important is that rail would become a python namespace instead of a module.   What that means is that import rail wouldn’t really do much (right now it pulls in pretty much everything).   
5. I'll make the new packages follow a more modern python package structure.  I.e., using pyproject.toml and having the code live in `src/rail/<whatever>`

**Comment by eacharles** [comment]
One knock-on effect is that using `rail.__file__` to find various test data wont work anymore.   Instead, I've added a variable in rail.core.utils called RAILDIR.   I.e., you can do:
```

from rail.core.utils import RAILDIR
datafile = os.path.join(RAILDIR, 'examples', 'some_data.fits')
```

**Comment by eacharles** [comment]
I'll fix that anywhere I find it in the test scripts and example notebooks.

**Comment by jfcrenshaw** [comment]
Things to add to install docs:
- you need to conda install `h5py` alongside RAIL. The best way to do this is to just install it when creating the environment:, e.g. `conda create -n rail -c conda-forge -y python=3.10 h5py`
- A list of each of the repos and what they're for
- I assume there won't be a required install order once everything is on pypi/conda-forge? But if there still is, we should note this
- a description of how this looks from the user side of things. Just something like "when you install these other packages, you access them like you access anything else in RAIL `from rail.something.something import ...`." Otherwise, people might think you have to do stuff like `from rail_pipelines import ...`

**Comment by eacharles** [comment]
Done in #233
