### ISSUE TITLE
Add a degrader to modify magnitude error depending on observing conditions

### ISSUE THREAD

**Issue by hangqianjun** [LSSTDESC/rail_attic#236]
We want to create a degrader package which sample a set of (correlated) observing conditions and compute the corresponding magnitude error for each galaxy.

Input files: observing conditions (e.g. OpSim outputs or supreme maps) in the form of healpix pixels over the survey footprint (e.g. DC2 wfd, or the full LSST footprint from the up-to-date OpSim version);

Functions: randomly assign galaxies into the pixels, and compute the corresponding magnitude error according to [Ivezic et al. 2019](https://arxiv.org/pdf/0805.2366.pdf) (This is alreay implemented in [lsst_error_model.py](https://github.com/LSSTDESC/RAIL/blob/main/rail/creation/degradation/lsst_error_model.py));

Output: a set of magnitude errors for each galaxy, which is then passed to generate the observed magnitude.

**Comment by jfcrenshaw** [comment]
This should be pretty easy to implement I think. 

We can get the mean number density of galaxies ($n$) from DC2. Then you can use PZFlow to generate 
$$N_\text{gal} = n \cdot N_\text{healpix} \cdot A_\text{healpix}$$ 
galaxies.

Then you just have to split the sample from PZFlow into $N_\text{healpix}$ different samples. You could use `np.array_split`, or you could add a healpix ID as a column in the dataframe use `df.groupby`. At that point, you can just apply `LSSTErrorModel` with the conditions for each healpix.

I can update the error model so that it makes it easier to pass in a different set of observing conditions for different samples. Do [the parameters](https://github.com/LSSTDESC/RAIL/blob/deefcaa5b6156eab52670d27e65ddb4f1f0d75da/rail/creation/degradation/lsst_error_model.py#L69-L121) in the error model cover everything you need?

**Comment by hangqianjun** [comment]
Thanks! I am also thinking along the same line: generating a healpix ID for each galaxy (with a weight related to the mean number density) and add as an extra column in the dataframe.
The parameters in the error model seem to cover most effects we want to include!
