### ISSUE TITLE
Stray installed directories

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/rail_attic#238]
When installing `pz-rail-hub` I get several packages which look like they should be sub-packages installed directly to the base `site-packages` directory.  

They are:
```
docs
examples
scripts
tests
```
From looking at them I assume they shouldn't be installed at all.

**Comment by joezuntz** [comment]
It looks like the `examples` direcrory is expected by BPZ. So should presumably be installed, but somewhere under rail.

**Comment by jfcrenshaw** [comment]
I think @sschmidt23 noticed this last week and might be working on a fix?

**Comment by sschmidt23** [comment]
I'd have to check to be sure it's the same problem, but I think that's actually from the installation of pz-rail (probably as as rail-hub dependency), and is due to how we have RAIL structured and where we have package_data stored.  I had to similarly restructure the DESC_BPZ package because it was copying package data from top-level directories rather than from within desc_bpz. 
I will create an issue for this if Joe doesn't beat me to it.
