### ISSUE TITLE
Paths to default files 

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/rail_attic#244]
Various stages (at least the ones listed below) have default parameters that assume we are running from the main RAIL directory. With the new installation using pip that's no longer going to be correct.  We should update the paths to their installed location.

I believe the official way to find resources like this that are installed with pip is to use the `importlib.resources` module. I think that should find them whether we have installed or are running directly from the RAIL dir.  The alternative is to use the `__file__` variable if I've misunderstood this.
This will have to wait until after #238 since that will presumably involve moving the files.

Affected stages:
```
GridSelection
SpecSelection
Inform_BPZ_lite
BPZ_lite
Inform_DelightPZ
delightPZ
```

**Comment by sschmidt23** [comment]
I believe at least `bpz_lite` has a parameters (`data_path`, `columns_file`, `spectra_file`) that, while defaulting to values relative to RAIL, can be set by the user.  I *think* I also put this into Delight as well.  So, I think it's up to the user to set these to alternate values if they are not running from the RAIL repo.  But, I could be missing something, and I'd have to check whether the equivalent is true for GridSelection and SpecSelection.

Hmm, though now I see what you are saying about using the __ file __ or import lib in order to set better defaults.  Maybe we can discuss that a bit before deciding what to do.

**Comment by sschmidt23** [comment]
I think that we're going to reorganize the RAIL directory structure a bit in a way that will address both this and #238. I'll take a crack at that now.
