### ISSUE TITLE
Add provenance tracking

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/rail_attic#25]
We should think about what provenance tracking information we want to add to the outputs.  Perhaps at least the date on which the code was run, maybe the hash for the particular commit/version of the GitHub code used, input files, config parameters?

**Comment by aimalz** [comment]
I think this may also apply to mock photometry from the creation module so am adding that tag. We might want to establish some bookkeeping (directory?) structure for keeping track of this (probably in the generalized end-to-end successor to [`main.py`](https://github.com/LSSTDESC/RAIL/blob/master/examples/main.py) rather than hardcoded into `rail`?).

**Comment by joezuntz** [comment]
Hi all. I plan to pull out the provenance tracking bits of TXPipe into a separate provenance library.  I'll let you know here when I do that in case it's useful here.

**Comment by aimalz** [comment]
I think we can safely close this one, thanks to @eacharles'  `ceci`-based refactoring.
