### ISSUE TITLE
Consider moving documentation to github pages?

### ISSUE THREAD

**Issue by eacharles** [LSSTDESC/rail_attic#263]
Basically, as we have more an more code, keeping the documention up to date will be a pain.   I think it will be easier to do that using the github pages mechanism, as it is doesn't require dealing with the extra step of the readthedocs build system.

**Comment by torluca** [comment]
I'll try to provide my opinion on this topic.
I understand that with more features implemented in time, the readthedocs build system might brake quite often. However I find in-text comments (properly formatted) extremely useful. This allowed me for instance to understand more easily RAIL from a pristine background. It also helps working directly "within" the code, rather than jumping between code and github page all the time. 
What if we provide a template file where the syntax for class, functions and relative documentations are implemented and people generate new files out of those, simply filling the gaps?
Pycharm has a similar feature where everytime you define a new function, by typing """ """ it automatically creates
:param name_parameters
:return 
etc.
I hope I haven't missed the point of the whole discussion.

**Comment by eacharles** [comment]
I agree that the doc strings are great.   The issue is that there are different formats out there.   By way of example, the format that pycharm is generating that you mention below is not the format that sphinx is expecting.  

Is there a way to tell pycharm to use the numpy format?

**Comment by torluca** [comment]
Yes, you can tell pycharm to use another format for the doc string

**Comment by aimalz** [comment]
Big questions to discuss in this issue: What do we need/want out of the autorendered documentation? What are the available options besides readthedocs with our current settings?

**Comment by eacharles** [comment]
Looks like Olivia has set up up to automatically make the notebooks.  I think that is enough for now.
