### ISSUE TITLE
Switch RAIL/estimation to output qp format rather than hdf5

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/rail_attic#33]
We should switch the outputs from the current hdf5 format to instead spit out qp compatible astropy tables.  RAIL/estimation currently has an iterator to process data in chunks, it looks like the astropy hdf5 tables allows for sequential writes via a file append so I think we can use that for now and maintain iterator functionality.  However, I'm not sure how well this will work with e.g. mpi4py when the chunks may be returned out of order, so we may have to redesign this to something more sophisticated for parallel processing in the near future.

**Comment by sschmidt23** [comment]
In implementing a change where we create qp Ensembles in the native format within RAIL/estimation and then write these to astropy hdf5 tables, I discovered that astropy Table `append` does not actually allow you to append to a single table, instead you can only append to additional 'path' tables within a single file.  This is good and bad: we can write the data in chunks with names where we can recover the original file order even if done out of sequence e.g. when done with multiple processors. But, we would have to do an additional post-processing step to astropy Table `vstack` the chunks into a single file after the code runs to get things into the final format that we want.  I'm now wondering if converting to qp within RAIL/estimation subclasses is worth it, or whether it might be more efficient to just have it as a post processing stage?  Doing it in the subclass and returning a qp Ensemble does force the code writer to make sure that qp functions properly, though we may take a slight performance penalty in the final stage of reading the data back in from file and merging the path chunks.  

Just something to think about, this may change if I find a smarter way to do things.

**Comment by aimalz** [comment]
I think we still want to have the RAIL i/o (well, input only for evaluation and output for both creation and estimation) use qp parameterizations, so maybe this issue is degenerate with proposing hdf5 as an option in LSSTDESC/qp#15? This also ties into the definition of shared data formats for intermediate files (that will be used in ways that are impractical for a database), which @joezuntz has been thinking about for TXPipe as well and which might (soon?) lead to another DESC repository so RAIL doesn't have to handle it at all. Meanwhile, am I correct in understanding that #17 aims to address the aspects of this issue that don't have to do with actual files @johannct? If this issue is indeed degenerate with those two, then perhaps it can be closed?

My only other thought on this is general uncertainty about why the final output of an estimator has to be a single file/table at all, particularly if the i/o functions are defined in some top-level `io_utils` module (or something like that, in qp or RAIL) that can stitch them together (or split them further) as part of loading if they really do have to be handled together. Would it even matter beyond the interaction between estimation and evaluation? And, if so, under what conditions would that i/o function not be usable by any other DESC code reads in RAIL's output posteriors?

**Comment by sschmidt23** [comment]
closed by #60
