### ISSUE TITLE
Main.yml fails to build wheel when somoclu is a dependency

### ISSUE THREAD

**Issue by olivialynn** [LSSTDESC/rail_attic#333]
In a fresh fork of RAIL, I have:

* a [workflow run](https://github.com/OliviaLynn/RAIL/actions/runs/4727096059/jobs/8387331893) that fails the Install dependencies step (with the pyproject.toml exactly as in RAIL)
* a [workflow run](https://github.com/OliviaLynn/RAIL/actions/runs/4727116515/jobs/8387376407) that passes the Install dependencies step (and fails the somoclu tests, because I've taken somoclu out of the pyproject.toml)

Going to keep looking into this, but if anyone has any insight, that would be fantastic.

_(For the record: I did change main.yml to use only python 3.10 to simplify isolating the issue. Also excluded the redundant `pip install numpy` line from main.yml, but I've checked since and the issue remains with or without it.)_

**Comment by eacharles** [comment]
Stupid question, but does it work in rail?On Apr 17, 2023, at 5:43 PM, Olivia R. Lynn ***@***.***> wrote:﻿
In a fresh fork of RAIL, I have:

a workflow run that fails the Install dependencies step (with the pyproject.toml exactly as in RAIL)
a workflow run that passes the Install dependencies step (and fails the somoclu tests, because I've taken somoclu out of the pyproject.toml)

Going to keep looking into this, but if anyone has any insight, that would be fantastic.
(For the record: I did change main.yml to use only python 3.10 to simplify isolating the issue. Also excluded the redundant pip install numpy line from main.yml, but I've checked since and the issue remains with or without it.)

**Comment by olivialynn** [comment]
Not for me--I did this in a fork after running into issues in my current PR on RAIL. 

So far removing the pip upgrade does seem promising, though I'm not sure this is an ideal solution.

**Comment by sschmidt23** [comment]
I see there is a separate `pip install numpy` in the main.yml GitHub action.  Josue pointed out that a new version of pip was released over the weekend, could there be some issue/change in dealing with multiple separate `pip install`s in a single action now, i.e. some sort of code isolation?  I'm totally guessing here, it could be coincidence that it is numpy giving us problems and being the only thing we install separately, but we could try removing that separate numpy install and see if anything changes.

**Comment by olivialynn** [comment]
I wondered about that too, but tried both with and without the explicit `pip install numpy` yesterday with no luck.
