### ISSUE TITLE
managing random seeds uniformly

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/rail_attic#41]
the np.random.seed call within the current estimation algorithms is probably not the way to go, as it does not allow the user to set it. Suggestion : add seed=87 in the `__init__` of the concerned algorithms, and add a `set_seed` in the base class

**Comment by eacharles** [comment]
Ok, there are a few aspects to this: 

1.  How to propagate seeds across modules
2. How to allow you to set the seed at a particular point in time, i.e., right before executing a unit test, as this is need to reproducibility. 
3. We will want all the modules that use seeds to have the same interface, so we should open new issue about collecting parameter names.

**Comment by eacharles** [comment]
We should be following the pattern use in KNN everywhere.

**Comment by sschmidt23** [comment]
For this issue, it looks like the only instance I see of not using `np.random.default_rng` is in grid_selection.py, so I think we just need to swap that over with two or three changes of instances of np.random.[stuff] and then we can close this.  Or am I missing something else that we need to do here?

**Comment by eacharles** [comment]
Depends a bit I think.

Do you want to be able to set a seed as part of a pipeline and be sure that it gets that seed?   Or do you just want it to grab the seed, and if you want to set the seed explicitly it a unit test that is on you?

**Comment by aimalz** [comment]
The LINCC Frameworks folks have introduced me to the idea of user stories as a way to figure out requirements for new feature implementations, so I'll make an attempt to use that structure here. So, (user) story time! 

> I'm debugging one stage of a pipeline and want to rerun it with the same random seed to test my fix. I need to know what random seed was used in every stage of my broken run (bookkeeping would be easier if it were the same across all stages in that run), and I need to be able to provide the same seed(s) to the new run (for the whole pipeline or each stage individually). 

> I want to get an idea of how much scatter in the final output quantities of my pipeline is imparted by a randomized aspect of one or more stages in the pipeline by rerunning that subset of stages with different random seeds several times but keeping the seed fixed between runs for the stages whose impact I'm not trying to constrain. I'll need to be able to check in the metadata of the stages/outputs to ensure that it was shared across the stages I want to hold constant and that it was indeed different between runs for the stages whose downstream scatter I'm trying to constrain.

Will it be possible to support both these use cases, and are there any others we should consider?

**Comment by sschmidt23** [comment]
I think I'm missing something, as I'm still not following: if we have it set up so that all stages that use a random number are using np.random.default_rng *and* have a config parameter with a default seed, then I think this accomplishes all stated cases above.  By default the randoms have the same default seed from the default parameter unless a different seed is specified by the user via a config parameter, and using default_rng isolates the randoms from any previous stages that have  a different seed.  I think the random seeds in this case are config parameters like any other, why do we need to treat them any differently?  (this is assuming that all uses of randoms *do* use default_rng so that they are isolated from other choices in randoms from previous stages).  If the config parameters are saved by, e.g. defining things in a pipeline yaml file with the seeds used, then you have  record of the seeds for every stage.

**Comment by eacharles** [comment]
I’m probably missing somethjng.  I’m not sure when the seed gets set, and the random number cycle is reset.-eOn Apr 21, 2023, at 11:13 AM, Sam Schmidt ***@***.***> wrote:﻿
I think I'm missing something, as I'm still not following: if we have it set up so that all stages that use a random number are using np.random.default_rng and have a config parameter with a default seed, then I think this accomplishes all stated cases above.  By default the randoms have the same default seed from the default parameter unless a different seed is specified by the user via a config parameter, and using default_rng isolates the randoms from any previous stages that have  a different seed.  I think the random seeds in this case are config parameters like any other, why do we need to treat them any differently?  (this is assuming that all uses of randoms do use default_rng so that they are isolated from other choices in randoms from previous stages).  If the config parameters are saved by, e.g. defining things in a pipeline yaml file with the seeds used, then you have  record of the seeds for every stage.

**Comment by sschmidt23** [comment]
I thought that we were moving toward defining with default_rng within each stage, e.g.
https://github.com/LSSTDESC/RAIL/blob/82da866035ebf3355ff4b97b68c7b7929c6e8a07/src/rail/estimation/algos/somocluSOM.py#L343
which includes setting the seed from the `seed` config parameter specified in `make_stage`.

**Comment by eacharles** [comment]
Ok, sounds like I’m just making noise then.  Sorry.

-e

**Comment by sschmidt23** [comment]
We can discuss briefly in the Monday tag-up to make sure I'm not missing anything as well, I could easily be forgetting some functionality that we want.

**Comment by aimalz** [comment]
Thanks @sschmidt23! I removed the question tag since there is a strategy already in place. This issue can be closed upon confirmation that this behavior is applied consistently across all stages and that the `seed` pan-config keyword is documented.

**Comment by aimalz** [comment]
When going through the estimators with @valentin-brekke, I noticed that [knnpz](https://github.com/LSSTDESC/RAIL/blob/main/src/rail/estimation/algos/knnpz.py#L109) doesn't actually refer to a `seed` config parameter when using a random number generator, so I think we have to check through everything in algos to double-check that this config parameter gets processed and propagated.

**Comment by sschmidt23** [comment]
Yes, I noticed that as well, I made changes on a local branch last week but didn't push because I got distracted with something else.  I'll do that shortly.  I just did a grep -r random src/ in the RAIL directory and looked through things to try to identify all the spots where seeds were used, the only unaddressed ones I saw where the knnpz one, randomPZ, and grid_selection.
