### ISSUE TITLE
Implementing Delight for PZ estimation

### ISSUE THREAD

**Issue by sylvielsstfr** [LSSTDESC/rail_attic#49]
I propose to implement in RAIL Delight for PZ, which has been implemented in
https://github.com/ixkael/Delight.

**Comment by aimalz** [comment]
Just catching up the issue with @sylvielsstfr's recent progress. 

As Delight is the first template-based code to be included in RAIL, it has some additional needs with respect to input files. @sschmidt23 mentioned wanting to also wrap BPZ in the foreseeable future, so this would be a good time to start thinking about making that process uniform in terms of where the files are located such that they can be shared among template-fitting codes within RAIL and how to deal with possible differences in the expected format of what would be the same physical information. But for now, the paths to the files will be put in [Delight's RAIL-specific config file](https://github.com/LSSTDESC/RAIL/blob/issue/49/delight/examples/configs/delightPZ.yaml) and the files themselves will be located with [the test data](https://github.com/LSSTDESC/RAIL/tree/issue/49/delight/tests/data).

Also, as with [GPz](https://github.com/pwhatfield/GPz), [Delight](https://github.com/sylvielsstfr/Delight) is a standalone package already but not installable via pip/conda through [RAIL's setup.py](https://github.com/LSSTDESC/RAIL/blob/master/setup.py), so we will need to provide installation instructions at some point. When the time comes, I think we can model those off of [CLMM's `install_clmm_pipeline()` function](https://github.com/LSSTDESC/CLMM/blob/master/INSTALL.md) provided as part of their documentation.

**Comment by johannct** [comment]
when the dust settles, Delight will need to be pip or conda installable, as much as possible. For pure python code it will be a requirement of DESC CO I think. We need to live in a clean world. All this of course for later. Is there a specific reason why you forked Boris' repo @sylvielsstfr ?

**Comment by sylvielsstfr** [comment]
Yes there are several reasons. 

A very first good one is that one function in scipy logsumexp has moved from from scipy.misc  to  scipy.special


see in 

https://github.com/sylvielsstfr/Delight/blob/master/delight/posteriors.py

And now the idea is not to have all the functions in script here

https://github.com/sylvielsstfr/Delight/tree/master/scripts

should be adapted to be called from RAIL (be python function instead of pure script with no main).

I am open for discussion about this interface.


Concerning good formating for package installation with pip and conda I am not an expert on this. I hope I can find help in PZ team ?


To have an idea of what I am proposing, please read ,

https://github.com/LSSTDESC/RAIL/blob/issue/49/delight/examples/HowToDelightPZ.md

**Comment by johannct** [comment]
I meant why not create a branch on Boris's repo.

**Comment by sylvielsstfr** [comment]
I didn't kow it was possible to modify Boris's repo (access rights question). 
That is why I had forked his repo in my own repo according what you said during the the hack week. 
My first idea whas to play with Delight and make some modifications.
Anyway we could think also to move a PZ DESC version of Delight under LSSTDESC area.
The question would be when, at what level of my readiness with Delight.

I am just adding some code to do the interface between core Delight functions with RAIL.
These interfaces are added at Delight repos level because those are inspired from script already written by Boris and those script are provided as a kind of user guide.
So these function bear the name of the original script in Delight.

But I am thinking to have also some functions inside RAIL. For example the data to be used for trainning and fitting phase would be converted in one ascii file which path is provided to Delight as an arguments written in an ascii configuration file.

I have no idea about the naming convention of those functions in RAIL.
Moreover I don't know if it would be necessary to have a common utility package available to each PZ estimator.

**Comment by sylvielsstfr** [comment]
I am nearly finished in connecting RAIL with Delight.
I will soon start the big and deep work of optimisation of Delight with test_DC2 datasets in RAIL context.

Should I make a pull request or should I continue on the optimisation ?

I will not be available from April 12th to May 10th.

How should I proceed ?

**Comment by johannct** [comment]
The more focused a PR is, the better it is for reviewers. So I would think that now is the time if the implementation, as is, is functional

**Comment by sylvielsstfr** [comment]
Could you explain what do you mean by "the more focused a PR is " ? 
Then when I understand I can trigger the code review.
Thanks.
SDC

**Comment by sschmidt23** [comment]
As we are approaching May 10th when Sylvie will be back, I was taking a look at the Delight branch.  I was able to get it installed and run on a high S/N subset, though it was *very* slow on cori, ~1.3 seconds per galaxy (24 minutes to do ~1800 galaxies).  Is this typical computation time for Delight?  I was using a single core, but even then, this seems quite slow, particularly since it was fitting with the default 8 CWWSB templates, and would be even slower if we used e.g. 100 empirical templates like we did in the PhotoZDC1 process.  Or, was this slow speed not typical, in which case there may be something off in my set up on cori.

I noticed that Delight produces a "full" PDF evaluated on a redshift grid, but there is an added function in the new `Delight.interfaces` that fits this to a Gaussian, which is what is actually written out in RAIL.  I think what we will want is the original PDF, not the Gaussian approximation.  I think that this should be easy to "fix" in the current implementation, I think that the call to `getDelightRedshiftEstimation` would just be changed to return the original PDFs rather than the Gaussians.

Delight also produces a bunch of temporary files in the ./tmp directory when running with the config file RAIL/examples/configs/delightPZ.yaml, we should probably clean these up and delete them in a post processing "clean up" step when the code is finished running.  

I see that Delight stores the SED templates and Filter curves in the Delight/data/ directory.  The filter curves for the LSST filters are slightly different than the ones assumed for DC2.  In the future we will probably want to store both SEDs and filter curves somewhere in rail/estimation/, maybe in a rail/estimation/data or rail/estimation/EXTRAS directory.  We will have to do some work to ensure that formats match up for multiple template-based codes when we do this, but that is beyond the scope of this PR.  For now, grabbing from Delight/data is fine, but it will change in the future.
